### ISSUE TITLE
Developer Licences

### ISSUE THREAD

**Issue by kunzflorian** [MORYX-Industry/Application-Developer-Training#5]
Dear Moryx-Team,

I have followed the training instructions 'till this point:

![image](https://github.com/MORYX-Industry/application-developer-training/assets/82371295/55dd99a6-fa95-4a55-8f99-eea33e478b96)

The developer licences from the generated project have been dropped within the CM-Center ...

![image](https://github.com/MORYX-Industry/application-developer-training/assets/82371295/6b45dd79-7dc3-4e66-9b9b-1b0e42b825f1)

... but results in the behaviour above.

Have I missed any instructions or is there a problem with the "developer licences" ?

Best regards,
Florian

**Comment by Toxantron** [comment]
I am a little suprised your CodeMeter is looking for a stick license. Did you have CodeMeter installed before starting MORYX?

**Comment by kunzflorian** [comment]
I tried a few ways, but I'm not aware about the order.

Installing CM in User/System Scope

When I reported it, I tried to run it within a Hyper-V-Host.
This weekened I tried it without Hypervisor and it had the same results.

In compare the the tuturial I had only had a number of 10 licence files.

I'll grab a new system and will report, if the behaviour stays the same.

Thanks in advance,
Florian

**Comment by kunzflorian** [comment]
Same result with following steps:

1. Installed CodeMeter 8.10a system-wide
2. Reboot (just to be sure)
3. Installing VS Tools
`dotnet tool install -g moryx.cli`
4. Generating Training-Project:
`moryx new PencilFactory --steps Assembling --products GraphitePencil`
5. Restore nuget & Build
6. Drag n Drop Licenses
7. Execute generated VS-Solution

Regards,
Florian

**Comment by Toxantron** [comment]
@seveneleven u got any idea as to why this would happen?

**Comment by seveneleven** [comment]
@kunzflorian You mentioned, that you had a smaller number of license files compared to the tutorial.

In your `PencilFactory.App.csproj` you should find these lines:

```
  <ItemGroup>
    <Compile Remove="$(NugetPackageRoot)\**\*.WibuCmRaU" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(NugetPackageRoot)\**\*.WibuCmRaU">
      <Link>%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>
```

If you remove these, all license files should appear within the solution explorer. But make sure to restore them after adding the licenses, so the project will compile.

**Comment by kunzflorian** [comment]
Things are getting more weird.

I had applied the instruction to an already existing project. The licences files stays the same

![with_itemgroup](https://github.com/MORYX-Industry/application-developer-training/assets/82371295/1de678a4-ae0d-4e9b-a480-4638a6c76076)

I created a new project removed the mentioned line before opening visual studio ...

![without_itemgroup](https://github.com/MORYX-Industry/application-developer-training/assets/82371295/f6e33e2a-4deb-495c-92a1-8e2fb672a899)

... after the nuget-restore, only 8 files appeared

i was mentioning the numbers, because of the screenshot in document ...

https://github.com/MORYX-Industry/application-developer-training/blob/main/chapter-1-basics.md#encountering-wupiexceptions

... which shows 15 of them.

**Comment by kunzflorian** [comment]
P.S. i ran a search on the licence files on my users nuget-folder. I have no clue how this CM-system works but the marked files seems to be a bit suspicious to me.

![image](https://github.com/MORYX-Industry/application-developer-training/assets/82371295/a6782bff-b089-428a-8fd9-f12ca83d3b91)

The last two files have the same name, but different folder(name)s where they are stored.

Is this pointing to something?

**Comment by seveneleven** [comment]
> The last two files have the same name, but different folder(name)s where they are stored.
> 
> Is this pointing to something?

No, this is intended. All packages ship with developer licenses. In this particular case, `Moryx.Workplans.Editing` and `Moryx.Workplans.Web` just require the same license. If your project would depend on only one of those packages, you should still get the license provided.

While you are already at the filesystem and refering to your initial post: The missing license depicted in the screenshot is required by `Moryx.Resources.Web`. So you should be fine if you add that by using the file explorer. 

Looking at your latest screenshot, that lists the `*.WibuCmRaU` files in your `.nuget` directory, I do not see a `Moryx.Resources.WibuCmRaU` at all. That might be a hint to not properly resolved dependencies. 

I will try to get this reproduced on a clean environment.

**Comment by kunzflorian** [comment]
Salute,

the missing licences are delivered by nuget now...

Thanks for fixing and best regards.

Florian
